name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install dependencies
        run: |
          go install github.com/bufbuild/buf/cmd/buf@v1.42.0
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Run build
        run: |
          buf generate
          go build ./cmd/riot-server

      - name: Run lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
