
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23.0'

    - name: Install dependencies
      run: |
        go install github.com/bufbuild/buf/cmd/buf@v1.42.0
        go get -u golang.org/x/lint/golint
        
    - name: Run build
      run: go build .
      
    - name: Run vet & lint
      run: |
        go vet .
        golint .